import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Organism/Navbar';
import Footer from '@/components/Organism/Footer';
import React, { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rumah Real Estate',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  hideNavbarFooter?: boolean;
}

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
  hideNavbarFooter = false,
}: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {!hideNavbarFooter && <Navbar />}
        {children}
        {!hideNavbarFooter && <Footer />}
      </body>
    </html>
  );
};

export default RootLayout;
